export enum EventStatus {
	CREATING = "CREATING",
	ACTIVE = "ACTIVE",
	ACCEPTING_INVITES = "ACCEPTING_INVITES",
	ACCEPTING_GUESTS = "ACCEPTING_GUESTS",
	APPROACHING_DEADLINE = "APPROACHING_DEADLINE",
	SOLD_OUT = "SOLD_OUT",
	DEADLINE_PASSED = "DEADLINE_PASSED",
	IN_PROGRESS = "IN_PROGRESS",
	EXPIRED = "EXPIRED",
	ENDED = "ENDED",
}
